apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-server
  namespace: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-server
  template:
    metadata:
      labels:
        app: spring-server
    spec:
      containers:
        - name: spring-server
          image: 932169417000.dkr.ecr.ap-northeast-2.amazonaws.com/no-repo:v6
          imagePullPolicy: Always

          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"

          env:
            - name: DB_HOST
              value: "database-1.camzq634ttje.ap-northeast-2.rds.amazonaws.com"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "nochu"
            - name: DB_USER
              value: "admin"
            - name: DDL_AUTO
              value: "none"
            - name: AWS_STATIC
              value: "ap-northeast-2"
            - name: AWS_BUCKET
              value: "nochu-bucket"
            - name: EMOTION_API_URL
              value: "http://gsmsv-1.yujun.kr:27570"
            - name: MUSIC_API_URL
              value: "http://gsmsv-1.yujun.kr:27570"

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-server-secret
                  key: DB_PASSWORD
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-server-secret
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: spring-server-secret
                  key: AWS_SECRET_KEY